version: '3'

services:
  db:
    image: postgres
    networks:
      - app-network

  nodejs:
    image: kitware/paraviewweb:pvw-egl-demo-v5.6.0
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  django:
    build: .
    image: dcmdb_django:latest
    command: python manage.py runserver 0.0.0.0:80
    container_name: django
    restart: unless-stopped
    volumes:
      - .:/code/
      - /mnt/sdb/data/resdata10/:/resultdata/
      # - ./sample:/resultdata/
    depends_on:
      - db
    networks:
      - app-network
      
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /mnt/sdb/data/resdata10:/usr/share/nginx/html/data/
      # - ./sample:/usr/share/nginx/html/data/
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
      - django
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

